name: Run Docker Container

on:
  workflow_dispatch:
  push:

jobs:
  run_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Pull Docker image
      run: docker pull w8877/study_xxqg:latest

    - name: Run Docker container
      run: |
        sudo service docker start
        docker run \
          --name study_xxqg \
          -d \
          --privileged=true \
          -p 8080:8080 \
          -v /etc/study_xxqg/:/opt/config/ \
          w8877/study_xxqg:latest
        wget -O config.yml "https://raw.githubusercontent.com/w1770946466/Everyday_News/main/XXQG_TiKu/config.yml" && mv -f config.yml ../etc/study_xxqg/config.yml
        docker exec -it study_xxqg bash
        cd opt
        ./study_xxqg
        
