name: Run Docker Container

on:
  workflow_dispatch:

jobs:
  run_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker image
      run: docker pull w8877/study_xxqg:latest

    - name: Run Docker container
      run: |
        service docker start
        docker run \
          --name study_xxqg \
          -d \
          --privileged=true \
          -p 8080:8080 \
          -v /etc/study_xxqg/:/opt/config/ \
          w8877/study_xxqg:latest
        sed -i 's//new_text/g' filename
        docker exec -it study_xxqg bash
        cd opt
        ./study_xxqg
        
